package com.devalr.domain.model

enum class SkyState {
    UNKNOWN,
    NIGHT_CLEAR,
    NIGHT_LOW_CLOUDS,
    NIGHT_VERY_CLOUDY,
    NIGHT_CLOUDY,
    NIGHT_HIGH_CLOUDS,
    NIGHT_CLOUDY_SOFT_RAIN,
    NIGHT_CLOUDY_STORM_SOFT_RAIN,
    DAY_CLEAR,
    DAY_LOW_CLOUDS,
    DAY_VERY_CLOUDY,
    DAY_CLOUDY,
    DAY_HIGH_CLOUDS,
    DAY_CLOUDY_SOFT_RAIN,
    DAY_CLOUDY_STORM_SOFT_RAIN,
}
