package com.devalr.domain.model.enums

enum class SkyState {
    DayClear,
    DayCloudy,
    DayCloudyLowSnow,
    DayCloudySnow,
    DayCloudyStorm,
    DayCloudyStormSoftRain,
    DayCloudySoftRain,
    DayHighClouds,
    DayLowClouds,
    DayLowCloudyLowRain,
    DayMists,
    DayVeryCloudy,
    DayVeryCloudyLowRain,
    DayVeryCloudyRain,
    DayVeryCloudySnow,
    DayVeryCloudyStorm,
    Haze,
    NightClear,
    NightCloudy,
    NightCloudyLowSnow,
    NightCloudySnow,
    NightCloudySoftRain,
    NightCloudyStorm,
    NightCloudyStormSoftRain,
    NightHighClouds,
    NightLowClouds,
    NightLowCloudyLowRain,
    NightMists,
    NightVeryCloudy,
    NightVeryCloudyLowRain,
    NightVeryCloudyRain,
    NightVeryCloudySnow,
    NightVeryCloudyStorm,
    Unknown
}
