on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GH_TOKEN }}

  build:
    needs: [ avoid_redundancy ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Give execute permission to Gradle wrapper
        run: chmod +x gradlew
      - name: Build app
        run: ./gradlew :app:build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Give execute permission to Gradle wrapper
        run: chmod +x gradlew
      - name: Run Unit Tests for Commons
        run: ./gradlew test
