on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GH_TOKEN }}

  build:
    needs: [ avoid_redundancy ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Give execute permission to Gradle wrapper
        run: chmod +x gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Build app
        run: ./gradlew :app:build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Give execute permission to Gradle wrapper
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Unit Tests for Commons
        run: ./gradlew test
